version: '3.8'

services:
  reddit-video-generator:
    build: .
    container_name: reddit-video-generator
    ports:
      - "5442:5000"
    volumes:
      - reddit-video-generator_reddit-video-api_assets:/app/assets
      - ./config.toml:/app/config.toml
    # Essential for Intel Arc GPU hardware acceleration
    devices:
      - /dev/dri:/dev/dri
    # Add video group access
    group_add:
      - video
    # Environment variables for Intel Arc
    environment:
      - LIBVA_DRIVER_NAME=iHD
      - LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri
      - INTEL_MEDIA_RUNTIME=/usr/lib/x86_64-linux-gnu/dri
    # Optional: privileged mode for full GPU access (use only if needed)
    # privileged: true
    restart: unless-stopped
volumes:
  reddit-video-generator_reddit-video-api_assets:
    name: reddit-video-generator_reddit-video-api_assets
