version: '3.8'

services:
  reddit-video-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8354:5000"
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./assets:/app/assets
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "api.py"]