services:
  reddit-video-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8354:5000"
    volumes:
      - ./config.toml:/app/config.toml
      - ./assets:/app/assets
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python3", "api.py"]
    networks:
      - reddit_network

networks:
  reddit_network:
    driver: bridge
