services:
  reddit-video-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8354:5000"
    volumes:
      - ./config.toml:/app/config.toml
      - ./assets:/app/assets
    environment:
      - PYTHONUNBUFFERED=1
      # Add DNS configuration
      - PYTHONIOENCODING=utf8
    dns:
      - 8.8.8.8  # Google's DNS
      - 8.8.4.4  # Google's secondary DNS
    dns_search: ""
    networks:
      - reddit-network
    extra_hosts:
      - "geolocation.onetrust.com:104.18.122.209"
      - "ip.taobao.com:140.205.94.189"
    command: ["python3", "api.py"]

networks:
  reddit-network:
    driver: bridge
