networks:
  reddit-network:
    driver: bridge
  video_generation:
    external: true
    name: Video Generation
services:
  reddit-video-api:
    build:
      context: .
      dockerfile: Dockerfile
    command:
    - python3
    - api.py
    dns:
    - 8.8.8.8
    - 8.8.4.4
    dns_search: ''
    environment:
    - PYTHONUNBUFFERED=1
    - PYTHONIOENCODING=utf8
    - PYTHONUNBUFFERED=1
    - PYTHONIOENCODING=utf8
    - INTEL_DEVICE_TYPE=gpu
    - ONEAPI_DEVICE_SELECTOR=level_zero:gpu
    - USE_IPEX=1
    extra_hosts:
    - geolocation.onetrust.com:104.18.122.209
    - ip.taobao.com:140.205.94.189
    networks:
      reddit-network:
        aliases:
        - reddit-api
      video_generation:
        ipv4_address: 10.20.0.11
    ports:
    - 8354:5000
    restart: unless-stopped
    volumes:
    - reddit-video-generator_reddit-video-api_assets:/app/assets
    - ./config.toml:/app/config.toml
    - /dev/dri:/dev/dri
    devices:
    - /dev/dri
volumes:
  reddit-video-generator_reddit-video-api_assets:
    name: reddit-video-generator_reddit-video-api_assets
